##
## MJackOS Project, main Makefile, compile all the source files
##
## @author: pulk66-s
## last update: 2023.09.20
##

# Includes
include mk/config.mk

# first rule: building everything
all: build_everything

# Build everything in the project
build_everything:
	@echo -e "${GREEN}Building everything${NC}"
	@make -C src/ all
	@echo -e "${GREEN}Building everything done${NC}"
